# Generated by Django 5.2.7 on 2025-11-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuelRequestsCore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='nome')),
                ('sobrenome', models.CharField(max_length=32, verbose_name='sobrenome')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
            ],
        ),
    ]
