# Generated by Django 5.2.7 on 2025-11-04 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuelRequestsCore', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='vendas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas'),
            preserve_default=False,
        ),
    ]
