# Generated by Django 5.2.7 on 2025-11-05 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuelRequestsCore', '0003_plano_vendas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cliente',
            new_name='clientes',
        ),
        migrations.RenameModel(
            old_name='plano',
            new_name='planos',
        ),
    ]
