# Generated by Django 5.2.7 on 2025-11-05 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuelRequestsCore', '0004_rename_cliente_clientes_rename_plano_planos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clientes',
            new_name='cliente',
        ),
        migrations.RenameModel(
            old_name='planos',
            new_name='plano',
        ),
    ]
